In [ ]:
import json 
import pandas as pd 
import numpy as np 
import os 

RESULTS_DIR = "/home/david/Desktop/yuna/HPA/evaluation/logits/pretrained"
def get_confidence_result(model='llava-v1.6-vicuna-7b-hf', dataset='vqa_1k_control'): 
    
    result = [] 
    filepath = f'{RESULTS_DIR}/{model}/{dataset}.jsonl' 
    if not os.path.exists(filepath): 
        print(filepath, 'does not exist')
        return 
    with open(filepath) as f:
        data_list = [json.loads(l) for l in f]
    
    if len(data_list) == 0: 
        os.remove(filepath)
        print(f'deleted', filepath )
        return 

    if len(data_list) < 1000:
        print(f'skip MODEL: {model} | DATASET: {dataset} | loaded {len(data_list)}')  
        return result
    else: 
       print(f'MODEL: {model} | DATASET: {dataset} | loaded {len(data_list)}')  
 
    for example in data_list:  
        output_answer_key = 'generated_answers' if 'generated_answers' in example.keys() else 'answers' 
        # dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers', 'generated_logits'])
        if 'generated_logits' not in example.keys(): 
            print('cannot process', example.keys(), example) 
            continue 
        for q in example['generated_logits'].keys():   
            logits = example['generated_logits'][q]['content']
            token_probs = np.exp([t['logprob'] for t in logits])
            confidence = token_probs.mean()  
            # print(f"{q}: {example[q]} \nAnswer: {example[output_answer_key][q]} conf: {confidence:.2f}")  
            result.append({
                'model': model, 
                'dataset': dataset, 
                'question_id': example['question_id'],
                'question': example[q], 
                'control_type': q, 
                'output': example[output_answer_key][q], 
                'confidence': round(confidence, 2)
            })
    return result

In [34]:
models = os.listdir(RESULTS_DIR) # ["Qwen3-VL-8B-Instruct"]   # 'llava-v1.6-vicuna-7b-hf'] #  
datasets = ['vqa_1k_control', 'vqa_1k_control_inst_blind'] # 'vqa_1k', 'vqa_1k_inst_blind',  

df = []
for model in models: 
    for ds in datasets: 
        df.append(get_confidence_result(model, ds)) 
df = pd.DataFrame([item for sublist in df for item in (sublist if sublist else [])]) 
df.groupby(['model', 'dataset', 'control_type'])['output'].count()

skip MODEL: Qwen3-VL-32B-Instruct | DATASET: vqa_1k_control | loaded 43
skip MODEL: Qwen3-VL-32B-Instruct | DATASET: vqa_1k_control_inst_blind | loaded 18
MODEL: llava-v1.6-vicuna-7b-hf | DATASET: vqa_1k_control | loaded 1000
MODEL: llava-v1.6-vicuna-7b-hf | DATASET: vqa_1k_control_inst_blind | loaded 1000
MODEL: llava-v1.6-vicuna-13b-hf | DATASET: vqa_1k_control | loaded 1000
MODEL: llava-v1.6-vicuna-13b-hf | DATASET: vqa_1k_control_inst_blind | loaded 1000
MODEL: llava-1.5-7b-hf | DATASET: vqa_1k_control | loaded 1000
MODEL: llava-1.5-7b-hf | DATASET: vqa_1k_control_inst_blind | loaded 1000
MODEL: Qwen3-VL-4B-Instruct | DATASET: vqa_1k_control | loaded 1000
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 524577, 'question': 'What number of clocks are on this tower?', 'question_id': 524577006, 'deictic_removed': 'What number of clocks are on the tower?', 'object_removed': 'What number of objects are on this tower?', 'weaker_object': 'What number of devices are on this tower?', 'subject_ablated': 'What number of the objects are on this tower?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000524577.jpg', 'answers': {'question': '1', 'deictic_removed': '1', 'object_removed': '1', 'weaker_object': '1', 'subject_ablated': '1'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 524577, 'question': 'Where is the clock located?', 'question_id': 524577024, 'deictic_removed': 'Where is the clock located?', 'object_removed': 'Where is the object located?', 'weaker_object': 'Where is the device located?', 'subject_ablated': 'Where is it located?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000524577.jpg', 'answers': {'question': 'on wall', 'deictic_removed': 'on wall', 'object_removed': 'building', 'weaker_object': 'wall', 'subject_ablated': 'street'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 524577, 'question': 'What type of numbers are on the clock?', 'question_id': 524577027, 'deictic_removed': 'What type of numbers are on the clock?', 'object_removed': 'What type of numbers are on the object?', 'weaker_object': 'What type of numbers are on the device?', 'subject_ablated': 'What type of numbers are on it?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000524577.jpg', 'answers': {'question': 'roman numerals', 'deictic_removed': 'roman numerals', 'object_removed': 'roman numerals', 'weaker_object': 'roman numerals', 'subject_ablated': 'roman'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 524799, 'question': 'How old is the child?', 'question_id': 524799000, 'deictic_removed': 'How old is the child?', 'object_removed': 'How old is the object?', 'weaker_object': 'How old is the person?', 'subject_ablated': 'How old is the object?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000524799.jpg', 'answers': {'question': '6', 'deictic_removed': '6', 'object_removed': 'young', 'weaker_object': 'child', 'subject_ablated': 'young'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 524850, 'question': 'How many engines do you see?', 'question_id': 524850001, 'deictic_removed': 'How many engines do you see?', 'object_removed': 'How many objects do you see?', 'weaker_object': 'How many machines do you see?', 'subject_ablated': 'How many of the objects do you see?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000524850.jpg', 'answers': {'question': '2', 'deictic_removed': '2', 'object_removed': 'too many to count', 'weaker_object': '2', 'subject_ablated': '10'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 525021, 'question': 'Does everyone have helmets on?', 'question_id': 525021007, 'deictic_removed': 'Does everyone have helmets on?', 'object_removed': 'Does everyone have objects on?', 'weaker_object': 'Does everyone have protective gear on?', 'subject_ablated': 'Does everyone have helmets on?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000525021.jpg', 'answers': {'question': 'no', 'deictic_removed': 'no', 'object_removed': 'no', 'weaker_object': 'no', 'subject_ablated': 'no'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 43816, 'question': 'Will the catcher catch the ball?', 'question_id': 43816008, 'deictic_removed': 'Will the catcher catch the ball?', 'object_removed': 'Will the object catch the ball?', 'weaker_object': 'Will the player catch the ball?', 'subject_ablated': 'Will the object catch the ball?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000043816.jpg', 'answers': {'question': 'no', 'deictic_removed': 'no', 'object_removed': 'no', 'weaker_object': 'no', 'subject_ablated': 'no'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 757, 'question': 'Are these animals all touching?', 'question_id': 757004, 'deictic_removed': 'Are animals all touching?', 'object_removed': 'Are objects all touching?', 'weaker_object': 'Are creatures all touching?', 'subject_ablated': 'Are the objects all touching?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000000757.jpg', 'answers': {'question': 'yes', 'deictic_removed': 'yes', 'object_removed': 'yes', 'weaker_object': 'yes', 'subject_ablated': 'yes'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 394002, 'question': "What's the brand of bike second from the left?", 'question_id': 394002002, 'deictic_removed': "What's the brand of bike second from the left?", 'object_removed': "What's the brand of object second from the left?", 'weaker_object': "What's the brand of vehicle second from the left?", 'subject_ablated': "What's the brand of the object second from the left?", 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000394002.jpg', 'answers': {'question': 'yamaha', 'deictic_removed': 'yamaha', 'object_removed': 'yamaha', 'weaker_object': 'yamaha', 'subject_ablated': 'yamaha'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 131869, 'question': 'What sport is being played?', 'question_id': 131869001, 'deictic_removed': 'What sport is being played?', 'object_removed': 'What sport is being played?', 'weaker_object': 'What sport is being played?', 'subject_ablated': 'What sport is being played?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000131869.jpg', 'answers': {'question': 'tennis', 'deictic_removed': 'tennis', 'object_removed': 'tennis', 'weaker_object': 'tennis', 'subject_ablated': 'tennis'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 263014, 'question': 'How many zebras?', 'question_id': 263014012, 'deictic_removed': 'How many zebras?', 'object_removed': 'How many objects?', 'weaker_object': 'How many animals?', 'subject_ablated': 'How many of the objects?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000263014.jpg', 'answers': {'question': '2', 'deictic_removed': '2', 'object_removed': '2', 'weaker_object': '2', 'subject_ablated': '2'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 525162, 'question': 'What color boat is the man riding in?', 'question_id': 525162004, 'deictic_removed': 'What color boat is the man riding in?', 'object_removed': 'What color object is the man riding in?', 'weaker_object': 'What color vehicle is the man riding in?', 'subject_ablated': 'What color is the object the man is riding in?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000525162.jpg', 'answers': {'question': 'red', 'deictic_removed': 'red', 'object_removed': 'red', 'weaker_object': 'red', 'subject_ablated': 'red'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 423396, 'question': 'If looking up where is the shadow for the clock?', 'question_id': 423396001, 'deictic_removed': 'If looking up where is the shadow for the clock?', 'object_removed': 'If looking up where is the shadow for the object?', 'weaker_object': 'If looking up where is the shadow for the device?', 'subject_ablated': 'If looking up where is the shadow for it?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000423396.jpg', 'answers': {'question': 'below', 'deictic_removed': 'below', 'object_removed': 'below', 'weaker_object': 'below', 'subject_ablated': 'below'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 132317, 'question': 'What is sitting on the laptop?', 'question_id': 132317000, 'deictic_removed': 'What is sitting on the laptop?', 'object_removed': 'What is sitting on the object?', 'weaker_object': 'What is sitting on the device?', 'subject_ablated': 'What is sitting on it?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000132317.jpg', 'answers': {'question': 'dragonfly', 'deictic_removed': 'dragonfly', 'object_removed': 'dragonfly', 'weaker_object': 'dragonfly', 'subject_ablated': 'dragonfly'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 1342, 'question': 'What kind of information does the yellow and white book look like it contains?', 'question_id': 1342072, 'deictic_removed': 'What kind of information does the yellow and white book look like it contains?', 'object_removed': 'What kind of information does the yellow and white object look like it contains?', 'weaker_object': 'What kind of information does the yellow and white publication look like it contains?', 'subject_ablated': 'What kind of information does it look like it contains?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000001342.jpg', 'answers': {'question': 'airplane shapes', 'deictic_removed': 'airplane shapes', 'object_removed': 'airplane shapes', 'weaker_object': 'airplane shapes', 'subject_ablated': 'airplane shapes'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 22103, 'question': 'Is there a fence between the girl and the giraffe?', 'question_id': 22103004, 'deictic_removed': 'Is there a fence between the girl and the giraffe?', 'object_removed': 'Is there a fence between the object and the object?', 'weaker_object': 'Is there a fence between the person and the animal?', 'subject_ablated': 'Is there a fence between the object and the object?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000022103.jpg', 'answers': {'question': 'yes', 'deictic_removed': 'yes', 'object_removed': 'yes', 'weaker_object': 'yes', 'subject_ablated': 'yes'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 2006, 'question': 'What colors are on the bus?', 'question_id': 2006001, 'deictic_removed': 'What colors are on the bus?', 'object_removed': 'What colors are on the object?', 'weaker_object': 'What colors are on the vehicle?', 'subject_ablated': 'What colors are on it?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000002006.jpg', 'answers': {'question': 'purple', 'deictic_removed': 'purple', 'object_removed': 'purple', 'weaker_object': 'purple', 'subject_ablated': 'purple'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 568315, 'question': 'Are the elephants sleeping?', 'question_id': 568315000, 'deictic_removed': 'Are the elephants sleeping?', 'object_removed': 'Are the objects sleeping?', 'weaker_object': 'Are the animals sleeping?', 'subject_ablated': 'Are the objects sleeping?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000568315.jpg', 'answers': {'question': 'no', 'deictic_removed': 'no', 'object_removed': 'no', 'weaker_object': 'no', 'subject_ablated': 'no'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 526675, 'question': 'What color are the flowers in the vase?', 'question_id': 526675002, 'deictic_removed': 'What color are the flowers in the vase?', 'object_removed': 'What color are the objects in the object?', 'weaker_object': 'What color are the plants in the container?', 'subject_ablated': 'What color are the objects in the object?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000526675.jpg', 'answers': {'question': 'yellow', 'deictic_removed': 'yellow', 'object_removed': 'red', 'weaker_object': 'yellow', 'subject_ablated': 'red'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 264660, 'question': 'How many pictures of children are there?', 'question_id': 264660000, 'deictic_removed': 'How many pictures of children are there?', 'object_removed': 'How many pictures of objects are there?', 'weaker_object': 'How many pictures of people are there?', 'subject_ablated': 'How many pictures of the objects are there?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000264660.jpg', 'answers': {'question': '2', 'deictic_removed': '2', 'object_removed': '10', 'weaker_object': '10', 'subject_ablated': '10'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 2521, 'question': 'Which way is the arrow pointing?', 'question_id': 2521002, 'deictic_removed': 'Which way is the arrow pointing?', 'object_removed': 'Which way is the object pointing?', 'weaker_object': 'Which way is the indicator pointing?', 'subject_ablated': 'Which way is it pointing?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000002521.jpg', 'answers': {'question': 'left', 'deictic_removed': 'left', 'object_removed': 'left', 'weaker_object': 'left', 'subject_ablated': 'left'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 527038, 'question': 'What website is shown?', 'question_id': 527038002, 'deictic_removed': 'What website is shown?', 'object_removed': 'What website is shown?', 'weaker_object': 'What website is shown?', 'subject_ablated': 'What website is shown?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000527038.jpg', 'answers': {'question': 'downtowntraveler.com', 'deictic_removed': 'downtowntraveler.com', 'object_removed': 'downtowntraveler.com', 'weaker_object': 'downtowntraveler.com', 'subject_ablated': 'downtowntraveler.com'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 133928, 'question': 'How many cranes are in this image?', 'question_id': 133928008, 'deictic_removed': 'How many cranes are in the image?', 'object_removed': 'How many objects are in the image?', 'weaker_object': 'How many machines are in the image?', 'subject_ablated': 'How many of the objects are in the image?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000133928.jpg', 'answers': {'question': '0', 'deictic_removed': '0', 'object_removed': '1', 'weaker_object': '1', 'subject_ablated': '1'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 133933, 'question': "Is this someone's house?", 'question_id': 133933006, 'deictic_removed': "Is this someone's house?", 'object_removed': "Is this someone's object?", 'weaker_object': "Is this someone's building?", 'subject_ablated': "Is this someone's object?", 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000133933.jpg', 'answers': {'question': 'yes', 'deictic_removed': 'yes', 'object_removed': 'yes', 'weaker_object': 'yes', 'subject_ablated': 'yes'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 396200, 'question': 'Is this kid on the right a professional skater?', 'question_id': 396200022, 'deictic_removed': 'Is this kid a professional skater?', 'object_removed': 'Is this object a professional skater?', 'weaker_object': 'Is this person a professional skater?', 'subject_ablated': 'Is the object a professional skater?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000396200.jpg', 'answers': {'question': 'no', 'deictic_removed': 'no', 'object_removed': 'yes', 'weaker_object': 'no', 'subject_ablated': 'yes'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 527528, 'question': 'What is the blue thing on the ground?', 'question_id': 527528001, 'deictic_removed': 'What is the blue thing on the ground?', 'object_removed': 'What is the blue object on the ground?', 'weaker_object': 'What is the blue object on the ground?', 'subject_ablated': 'What is the blue object on the ground?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000527528.jpg', 'answers': {'question': 'can', 'deictic_removed': 'can', 'object_removed': 'can', 'weaker_object': 'can', 'subject_ablated': 'can'}}
cannot process dict_keys(['image_id', 'question', 'question_id', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated', 'image', 'answers']) {'image_id': 488942, 'question': 'Is this a sightseeing attraction?', 'question_id': 488942005, 'deictic_removed': 'Is this a sightseeing attraction?', 'object_removed': 'Is this an object attraction?', 'weaker_object': 'Is this a tourist attraction?', 'subject_ablated': 'Is this an attraction?', 'image': '/home/david/Desktop/yuna/data/val2014/COCO_val2014_000000488942.jpg', 'answers': {'question': 'yes', 'deictic_removed': 'yes', 'object_removed': 'yes', 'weaker_object': 'yes', 'subject_ablated': 'yes'}}

model                     dataset                    control_type
Qwen3-VL-4B-Instruct      vqa_1k_control_inst_blind  deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
Qwen3-VL-8B-Instruct      vqa_1k_control             deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
llava-1.5-7b-hf           vqa_1k_control             deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
                          vqa_1k_control_inst_blind  deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
llava-v1.6-mistral-7b-hf  vqa_1k_control             deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
                          vqa_1k_control_inst_blind  deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
llava-v1.6-vicuna-13b-hf  vqa_1k_control             deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
                          vqa_1k_control_inst_blind  deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
llava-v1.6-vicuna-7b-hf   vqa_1k_control             deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
                          vqa_1k_control_inst_blind  deictic_removed    1000
                                                     object_removed     1000
                                                     question           1000
                                                     subject_ablated    1000
                                                     weaker_object      1000
Name: output, dtype: int64

In [ ]:
df['confidence'] = df['confidence'].astype(str)
df.pivot_table(
    index=['model','question_id', 'control_type', ],
    columns=['dataset'],
    values=['question', 'output', 'confidence'],
    aggfunc=lambda x: ' | '.join(x)
).reindex(['question', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated'], level='control_type').dropna(axis=0) # .to_csv('./example_results_confidence.csv')

In [41]:
control_type_order = ['question', 'deictic_removed', 'object_removed', 'weaker_object', 'subject_ablated']
table = df.pivot_table(
    index=['control_type'],
    columns=['dataset', 'model'],
    values=['confidence'],
    aggfunc=['mean', 'count']
)
# Reindex the index to the desired order
table = table.reindex(control_type_order)
table.round(3)

                                mean                                           \
                          confidence
dataset               vqa_1k_control
model           Qwen3-VL-8B-Instruct llava-1.5-7b-hf llava-v1.6-mistral-7b-hf
control_type
question                       0.952           0.847                    0.910
deictic_removed                0.952           0.847                    0.910
object_removed                 0.944           0.822                    0.893
weaker_object                  0.948           0.842                    0.904
subject_ablated                0.946           0.819                    0.891

                                                                  \

dataset
model           llava-v1.6-vicuna-13b-hf llava-v1.6-vicuna-7b-hf
control_type
question                           0.875                   0.874
deictic_removed                    0.874                   0.873
object_removed                     0.847                   0.850
weaker_object                      0.865                   0.867
subject_ablated                    0.844                   0.846

                                                           \

dataset         vqa_1k_control_inst_blind
model                Qwen3-VL-4B-Instruct llava-1.5-7b-hf
control_type
question                            0.927           0.812
deictic_removed                     0.926           0.812
object_removed                      0.929           0.811
weaker_object                       0.924           0.812
subject_ablated                     0.930           0.812

                                                                   \

dataset
model           llava-v1.6-mistral-7b-hf llava-v1.6-vicuna-13b-hf
control_type
question                           0.865                    0.795
deictic_removed                    0.866                    0.796
object_removed                     0.863                    0.793
weaker_object                      0.860                    0.788
subject_ablated                    0.864                    0.793

                                                       count                  \
                                                  confidence
dataset                                       vqa_1k_control
model           llava-v1.6-vicuna-7b-hf Qwen3-VL-8B-Instruct llava-1.5-7b-hf
control_type
question                          0.816                 1000            1000
deictic_removed                   0.815                 1000            1000
object_removed                    0.816                 1000            1000
weaker_object                     0.815                 1000            1000
subject_ablated                   0.819                 1000            1000

                                                                   \

dataset
model           llava-v1.6-mistral-7b-hf llava-v1.6-vicuna-13b-hf
control_type
question                            1000                     1000
deictic_removed                     1000                     1000
object_removed                      1000                     1000
weaker_object                       1000                     1000
subject_ablated                     1000                     1000

                                                                   \

dataset                                 vqa_1k_control_inst_blind
model           llava-v1.6-vicuna-7b-hf      Qwen3-VL-4B-Instruct
control_type
question                           1000                      1000
deictic_removed                    1000                      1000
object_removed                     1000                      1000
weaker_object                      1000                      1000
subject_ablated                    1000                      1000

                                                          \

dataset
model           llava-1.5-7b-hf llava-v1.6-mistral-7b-hf
control_type
question                   1000                     1000
deictic_removed            1000                     1000
object_removed             1000                     1000
weaker_object              1000                     1000
subject_ablated            1000                     1000



dataset
model           llava-v1.6-vicuna-13b-hf llava-v1.6-vicuna-7b-hf
control_type
question                            1000                    1000
deictic_removed                     1000                    1000
object_removed                      1000                    1000
weaker_object                       1000                    1000
subject_ablated                     1000                    1000

In [ ]:
df = analyze_confidences(results)
df.head()

,image_id,question_id,conf_question,pred_question,correct_question,acc_question,conf_deictic_removed,pred_deictic_removed,correct_deictic_removed,acc_deictic_removed,...,correct_object_removed,acc_object_removed,conf_weaker_object,pred_weaker_object,correct_weaker_object,acc_weaker_object,conf_subject_ablated,pred_subject_ablated,correct_subject_ablated,acc_subject_ablated
0,524577,524577006,0.999989,<|im_end|>,1,False,0.999986,<|im_end|>,1,False,...,1,False,0.976570,<|im_end|>,1,False,0.000000,2,12,False
1,524577,524577024,0.000000,building,on building,False,0.000000,building,on building,False,...,outside,False,0.733708,<|im_end|>,wall,False,0.665584,<|im_end|>,outside,False
2,524577,524577027,0.000000,abic,arabic,False,0.000000,abic,arabic,False,...,arabic,False,0.000000,abic,arabic,False,0.000000,abic,arabic,False
3,524799,524799000,0.360309,<|im_end|>,6,False,0.360309,<|im_end|>,6,False,...,young,False,0.393762,<|im_end|>,7,False,0.409214,<|im_end|>,young,False
4,524850,524850001,0.999949,<|im_end|>,2,False,0.999949,<|im_end|>,2,False,...,2,False,0.885704,<|im_end|>,1,False,0.657866,<|im_end|>,2,False